drop table system;
drop table RESOURCE_USAGE;
CREATE TABLE SYSTEM( 
    SYSTEM_ID VARCHAR2(5), 
    SYSTEM_NAME VARCHAR2(15)
);

INSERT INTO SYSTEM VALUES('XXX','혜화DB'); 
INSERT INTO SYSTEM VALUES('YYY','강남DB'); 
INSERT INTO SYSTEM VALUES('ZZZ','영등포DB');

CREATE TABLE RESOURCE_USAGE(
    SYSTEM_ID VARCHAR2(5), 
    RESOURCE_NAME VARCHAR2(10)
);

INSERT INTO RESOURCE_USAGE VALUES('XXX','FTP'); 
INSERT INTO RESOURCE_USAGE VALUES('YYY','FTP'); 
INSERT INTO RESOURCE_USAGE VALUES('YYY','TELNET'); 
INSERT INTO RESOURCE_USAGE VALUES('YYY','EMAIL'); 
COMMIT;
