SELECT
SUBSTR(주소, 1, INSTR(주소, ' ','1','2')-1)
FROM POLLUTION;

ALTER TABLE POLLUTION ADD 주소 VARCHAR(300);
update POLLUTION set 주소 = COALESCE(소재지전체주소, 도로명전체주소);
update POLLUTION set 주소 = SUBSTR(주소, 1, INSTR(주소, ' ','1','2')-1);
commit;

select * from POLLUTION;

Alter TABLE POLLUTION
Drop COLUMN 소재지전체주소;

Alter TABLE POLLUTION
Drop COLUMN 도로명전체주소;

Alter TABLE POLLUTION
Drop COLUMN 영업상태구분코드;

--컬럼 숨김
ALTER TABLE POLLUTION MODIFY 배출시설조업시간 INVISIBLE;
ALTER TABLE POLLUTION MODIFY 배출시설연간가동일수 INVISIBLE;
ALTER TABLE POLLUTION MODIFY 방지시설조업시간 INVISIBLE;
ALTER TABLE POLLUTION MODIFY 방지시설연간가동일수 INVISIBLE;

--컬럼 보이기
ALTER TABLE POLLUTION MODIFY 배출시설조업시간 VISIBLE;
ALTER TABLE POLLUTION MODIFY 배출시설연간가동일수 VISIBLE;
ALTER TABLE POLLUTION MODIFY 방지시설조업시간 VISIBLE;
ALTER TABLE POLLUTION MODIFY 방지시설연간가동일수 VISIBLE;