INSERT INTO DEPT VALUES(50,'연구소1','서울');
INSERT INTO DEPT(DNAME,LOC) VALUES('중부지점','대구');
INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES(51,'연구소2','대전');
INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES(52, '북부지점',NULL);
INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES(53, '남부지점','');
INSERT INTO DEPT(DEPTNO,DNAME) VALUES(54,'서부지점');
COMMIT;
rollback;

SELECT distinct sid
FROM v$mystat;