SELECT * FROM TAB;

SELECT COUNT(*) FROM ZIPCODE; # 52,120건
SELECT COUNT(*) FROM PRODUCT; # 288건
SELECT COUNT(*) FROM CUSTOMER; # 570만건 이상
SELECT COUNT(*) FROM ORDERS; # 5,000만건 이상
SELECT COUNT(*) FROM ORDER_ITEMS; # 2억건 이상